_Restore test_database.py_

# coding: utf-8
import sys
sys.stdout.reconfigure(encoding='utf-8')

content = '# coding: utf-8\n'
content += '"""Tests for database layer."""\n'
content += 'from __future__ import annotations\n'
content += 'from unittest.mock import AsyncMock, MagicMock\n'
content += 'import pytest\n'
content += 'from src.database import Alert, Candle, clear_alerts, close_engine, get_alerts, get_recent_candles, init_db\n'
content += '\n'
content += '@pytest.mark.asyncio\n'
content += 'async def test_init_db():\n'
content += '    engine_mock = MagicMock()\n'
content += '    result = await init_db(engine_mock)\n'
content += '    assert result is None\n'
content += '\n'
content += '@pytest.mark.asyncio\n'
content += 'async def test_get_alerts_empty():\n'
content += '    session_maker = MagicMock()\n'
content += '    session_mock = AsyncMock()\n'
content += '    result_mock = MagicMock()\n'
content += '    scalars_mock = MagicMock()\n'
content += '    scalars_mock.all.return_value = []\n'
content += '    result_mock.scalars.return_value = scalars_mock\n'
content += '    session_mock.execute.return_value = result_mock\n'
content += '    session_mock.__aenter__.return_value = session_mock\n'
content += '    session_maker.return_value = session_mock\n'
content += '    alerts = await get_alerts(session_maker, limit=10)\n'
content += '    assert alerts == []\n'
content += '\n'
content += '@pytest.mark.asyncio\n'
content += 'async def test_get_alerts_with_data():\n'
content += '    alert = Alert(pct_change=0.02, eth_price=1000.0, btc_price=20000.0)\n'
content += '    session_maker = MagicMock()\n'
content += '    session_mock = AsyncMock()\n'
content += '    result_mock = MagicMock()\n'
content += '    scalars_mock = MagicMock()\n'
content += '    scalars_mock.all.return_value = [alert]\n'
content += '    result_mock.scalars.return_value = scalars_mock\n'
content += '    session_mock.execute.return_value = result_mock\n'
content += '    session_mock.__aenter__.return_value = session_mock\n'
content += '    session_maker.return_value = session_mock\n'
content += '    alerts = await get_alerts(session_maker, limit=10)\n'
content += '    assert len(alerts) == 1\n'
content += '    assert alerts[0].pct_change == 0.02\n'
content += '\n'
content += '@pytest.mark.asyncio\n'
content += 'async def test_clear_alerts():\n'
content += '    session_maker = MagicMock()\n'
content += '    session_mock = AsyncMock()\n'
content += '    execute_mock = MagicMock()\n'
content += '    execute_mock.rowcount = 2\n'
content += '    session_mock.execute.return_value = execute_mock\n'
content += '    session_mock.__aenter__.return_value = session_mock\n'
content += '    session_maker.return_value = session_mock\n'
content += '    await clear_alerts(session_maker)\n'
content += '    session_mock.commit.assert_awaited_once()\n'
content += '\n'
content += '@pytest.mark.asyncio\n'
content += 'async def test_get_recent_candles_empty():\n'
content += '    session_maker = MagicMock()\n'
content += '    session_mock = AsyncMock()\n'
content += '    result_mock = MagicMock()\n'
content += '    scalars_mock = MagicMock()\n'
content += '    scalars_mock.all.return_value = []\n'
content += '    result_mock.scalars.return_value = scalars_mock\n'
content += '    session_mock.execute.return_value = result_mock\n'
content += '    session_mock.__aenter__.return_value = session_mock\n'
content += '    session_maker.return_value = session_mock\n'
content += '    candles = await get_recent_candles(session_maker, \"ETHUSDT\", limit=10)\n'
content += '    assert candles == []\n'
content += '\n'
content += '@pytest.mark.asyncio\n'
content += 'async def test_get_recent_candles_with_data():\n'
content += '    from datetime import datetime, timezone\n'
content += '    candle = Candle(\n'
content += '        symbol=\"ETHUSDT\",\n'
content += '        timestamp=datetime.now(timezone.utc),\n'
content += '        open=1000.0, high=1010.0, low=990.0, close=1005.0, volume=100.0,\n'
content += '    )\n'
content += '    session_maker = MagicMock()\n'
content += '    session_mock = AsyncMock()\n'
content += '    result_mock = MagicMock()\n'
content += '    scalars_mock = MagicMock()\n'
content += '    scalars_mock.all.return_value = [candle]\n'
content += '    result_mock.scalars.return_value = scalars_mock\n'
content += '    session_mock.execute.return_value = result_mock\n'
content += '    session_mock.__aenter__.return_value = session_mock\n'
content += '    session_maker.return_value = session_mock\n'
content += '    candles = await get_recent_candles(session_maker, \"ETHUSDT\", limit=10)\n'
content += '    assert len(candles) == 1\n'
content += '    assert candles[0].symbol == \"ETHUSDT\"\n'
content += '\n'
content += '@pytest.mark.asyncio\n'
content += 'async def test_get_recent_candles_error():\n'
content += '    session_maker = MagicMock()\n'
content += '    session_mock = AsyncMock()\n'
content += '    session_mock.__aenter__.return_value.execute.side_effect = Exception(\"db error\")\n'
content += '    session_maker.return_value = session_mock\n'
content += '    candles = await get_recent_candles(session_maker, \"ETHUSDT\", limit=10)\n'
content += '    assert candles == []\n'
content += '\n'
content += '@pytest.mark.asyncio\n'
content += 'async def test_get_alerts_error():\n'
content += '    session_maker = MagicMock()\n'
content += '    session_mock = AsyncMock()\n'
content += '    session_mock.__aenter__.return_value.execute.side_effect = Exception(\"db error\")\n'
content += '    session_maker.return_value = session_mock\n'
content += '    alerts = await get_alerts(session_maker, limit=10)\n'
content += '    assert alerts == []\n'
content += '\n'
content += '@pytest.mark.asyncio\n'
content += 'async def test_close_engine():\n'
content += '    engine_mock = AsyncMock()\n'
content += '    engine_mock.dispose = AsyncMock()\n'
content += '    await close_engine(engine_mock)\n'
content += '    engine_mock.dispose.assert_awaited_once()\n'

with open('C:/Users/roman/Desktop/PC/MarketPulse/tests/test_database.py', 'w', encoding='utf-8') as f:
    f.write(content)
print('DONE')

